# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7fade8c65d20bc89f86637c7d08e69a37f93efe0ebba54015cd2baabe5976fe5f60337eb07df27ce91c4f8b588a948a7c9ac150e4c75816713bbcef3ad6cbd

test:
  secret_key_base: a24751498e088c4c5d98f1ccf23f176db0a25ba12b42c9e5dd28f0d45615ca8fb58aea2f0d13b098be2036e7e8936dbcd13ececdada7e0561562493ddcea4006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
